[package]
name = "spite-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
jiff.workspace = true
jiff-tzdb.workspace = true
spite-bigint.workspace = true
spite-core.workspace = true
spite-heap.workspace = true
spite-parser.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
