[package]
name = "spite-test262"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
spite-core.workspace = true
spite-parser.workspace = true
spite-runtime.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
