#!/usr/bin/env python3
"""Independent exact-sum reference using Python Fraction and binary64 rounding."""

import argparse
from fractions import Fraction
import math
from pathlib import Path
import random
import struct


def bits(value):
    return int.from_bytes(struct.pack(">d", value), "big")


def number(encoding):
    return struct.unpack(">d", encoding.to_bytes(8, "big"))[0]


def reference(values):
    exact = sum((Fraction.from_float(value) for value in values), Fraction())
    try:
        return float(exact)
    except OverflowError:
        return -math.inf if exact < 0 else math.inf


def generate():
    minimum = number(1)
    maximum = number(0x7FEFFFFFFFFFFFFF)
    cases = []
    for encoding in (
        1, 0x000FFFFFFFFFFFFF, 0x0010000000000000, 0x0010000000000001,
        0x3FB999999999999A, 0x3FEFFFFFFFFFFFFF, 0x3FF0000000000000,
        0x3FF0000000000001, 0x4340000000000001, 0x7FEFFFFFFFFFFFFF,
    ):
        value = number(encoding)
        cases.extend(([value], [value, value, -value],
                      [value, -value, minimum], [value, minimum]))
    # Exact halfway sums, adjacent odd significands, and sticky contributions
    # many accumulator words below the retained binary64 significand.
    for exponent in (-1021, -1000, -960, -896, -512, -64, -53, -1,
                     0, 1, 52, 64, 512, 960, 1023):
        value = math.ldexp(1.0, exponent)
        halfway = math.ldexp(1.0, exponent - 53)
        cases.extend(([value, halfway], [value, halfway, minimum],
                      [value, halfway, -minimum],
                      [math.nextafter(value, math.inf), halfway]))
    halfway = math.ldexp(1.0, 970)
    cases.extend(([maximum, halfway], [maximum, halfway, -minimum],
                  [maximum, halfway, minimum], [maximum, maximum, -maximum]))
    rng = random.Random(0x53554D50524543495345)
    for _ in range(128):
        values = []
        while len(values) < 6:
            value = number(rng.getrandbits(64))
            if math.isfinite(value):
                values.append(value)
        # Include cancellation after large transient sums.
        cases.append(values + [-values[0], -values[1]])
    lines = [
        "# Generated by tools/generate-number-sum-fixtures.py; sec-math.sumprecise.",
        "# comma-separated binary64 input bits\texact sum rounded once (ties-even)",
    ]
    for values in cases:
        for inputs in (values, [-value for value in values]):
            encoded = ",".join(f"{bits(value):016x}" for value in inputs)
            lines.append(f"{encoded}\t{bits(reference(inputs)):016x}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = (Path(__file__).resolve().parents[1]
            / "crates/spite-runtime/tests/fixtures/number_sum.tsv")
    expected = generate()
    if args.check:
        if path.read_text() != expected:
            raise SystemExit("Number sum fixtures need regeneration")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected)


if __name__ == "__main__":
    main()
