"""Generate ECMAScript identifier tables from a pinned Unicode data file."""

import argparse
import hashlib
from pathlib import Path
import urllib.request

VERSION = "18.0.0"
URL = f"https://www.unicode.org/Public/{VERSION}/ucd/DerivedCoreProperties.txt"
SHA256 = "09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9"
OUTPUT = Path(__file__).resolve().parent.parent / "crates/spite-core/src/unicode_data.rs"


def generate(data):
    if hashlib.sha256(data).hexdigest() != SHA256:
        raise ValueError("Unicode data does not match the pinned SHA-256")
    properties = {"ID_Start": [], "ID_Continue": []}
    for line in data.decode("utf-8").splitlines():
        fields = [field.strip() for field in line.split("#", 1)[0].split(";")]
        if len(fields) != 2 or fields[1] not in properties:
            continue
        bounds = fields[0].split("..")
        start, end = int(bounds[0], 16), int(bounds[-1], 16)
        if not (0 <= start <= end <= 0x10FFFF) or (start <= 0xDFFF and end >= 0xD800):
            raise ValueError("invalid Unicode scalar range")
        ranges = properties[fields[1]]
        if ranges and start <= ranges[-1][1]:
            raise ValueError("overlapping or unordered Unicode ranges")
        if ranges and start == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], end)
        else:
            ranges.append((start, end))
    lines = [
        "// Generated by tools/generate-unicode.py. Do not edit.",
        f"// Source: {URL}",
        f"// SHA-256: {SHA256}",
        "// Copyright © 2026 Unicode, Inc. See third-party/unicode/LICENSE.",
        "",
        "/// Unicode version used for ECMAScript identifier properties.",
        f'pub const UNICODE_VERSION: &str = "{VERSION}";',
    ]
    for name, ranges in properties.items():
        if not ranges:
            raise ValueError(f"missing property: {name}")
        lines += ["", f"pub(crate) const {name.upper()}: &[(u32, u32)] = &["]
        lines += [f"    (0x{start:04x}, 0x{end:04x})," for start, end in ranges]
        lines += ["];"]
    return ("\n".join(lines) + "\n").encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", type=Path, help="local pinned UCD file (otherwise download)")
    parser.add_argument("--check", action="store_true", help="verify the checked-in tables without writing")
    args = parser.parse_args()
    if args.source:
        data = args.source.read_bytes()
    else:
        with urllib.request.urlopen(URL, timeout=60) as response:
            data = response.read(4 * 1024 * 1024)
    generated = generate(data)
    if args.check:
        if OUTPUT.read_bytes() != generated:
            raise SystemExit("Unicode tables differ from the pinned data. Regenerate and review them.")
        print(f"Verified Unicode {VERSION} identifier tables.")
    else:
        OUTPUT.write_bytes(generated)
        print(f"Generated Unicode {VERSION} identifier tables.")


if __name__ == "__main__":
    main()
