"""Generate Unicode default casing, simple folding and contextual properties."""

import argparse
import hashlib
from pathlib import Path
import urllib.request

VERSION = "18.0.0"
SOURCES = {
    "UnicodeData.txt": "0736451de439ae7baf1425136617da495e09ee5afbe6e394374db7009ea08950",
    "SpecialCasing.txt": "8538dea57c184f1ef3783885ea79677b10f6efa06423717157e63712f14d1ad2",
    "DerivedCoreProperties.txt": "09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9",
    "CaseFolding.txt": "a004797658a457bec4dc11683e39f69249ea3b595b752dbea6721c4c9f587b0d",
}
OUTPUT = Path(__file__).resolve().parent.parent / "crates/spite-core/src/case_data.rs"


def scalar(value):
    cp = int(value, 16)
    if not (0 <= cp <= 0x10FFFF) or 0xD800 <= cp <= 0xDFFF:
        raise ValueError("invalid Unicode scalar")
    return cp


def generate(sources):
    for name, digest in SOURCES.items():
        if hashlib.sha256(sources[name]).hexdigest() != digest:
            raise ValueError(f"{name} differs from the pinned SHA-256")
    mappings = {"LOWERCASE": {}, "UPPERCASE": {}}
    for line in sources["UnicodeData.txt"].decode().splitlines():
        fields = line.split(";")
        if len(fields) != 15:
            raise ValueError("invalid UnicodeData record")
        for name, column in [("LOWERCASE", 13), ("UPPERCASE", 12)]:
            if fields[column]:
                cp, target = scalar(fields[0]), scalar(fields[column])
                if cp in mappings[name]:
                    raise ValueError("duplicate UnicodeData mapping")
                mappings[name][cp] = [target]
    contexts = []
    for line in sources["SpecialCasing.txt"].decode().splitlines():
        fields = [f.strip() for f in line.split("#", 1)[0].split(";")]
        if len(fields) == 1:
            continue
        if len(fields) != 5 and len(fields) != 6:
            raise ValueError("invalid SpecialCasing record")
        cp = scalar(fields[0])
        lower, upper = [[scalar(v) for v in fields[i].split()] for i in (1, 3)]
        condition = fields[4].split()
        if condition:
            if condition[0] in ("lt", "tr", "az"):
                continue  # Language tailoring is outside Unicode default conversion.
            if condition != ["Final_Sigma"] or cp != 0x03A3 or lower != [0x03C2] or upper != [cp]:
                raise ValueError("unhandled language-insensitive case condition")
            contexts.append(cp)
            continue
        for name, target in [("LOWERCASE", lower), ("UPPERCASE", upper)]:
            mappings[name][cp] = target
    if contexts != [0x03A3]:
        raise ValueError("unexpected contextual case mappings")
    simple_folding = {}
    seen_folds = set()
    previous = -1
    for line in sources["CaseFolding.txt"].decode().splitlines():
        fields = [f.strip() for f in line.split("#", 1)[0].split(";")]
        if len(fields) == 1:
            continue
        if len(fields) != 4 or fields[3] or fields[1] not in ("C", "F", "S", "T"):
            raise ValueError("invalid CaseFolding record")
        cp, status = scalar(fields[0]), fields[1]
        target = [scalar(v) for v in fields[2].split()]
        if not target or cp < previous or (cp, status) in seen_folds:
            raise ValueError("empty, unordered or duplicate case folding")
        previous = cp
        seen_folds.add((cp, status))
        if status in ("C", "S"):
            if len(target) != 1 or cp in simple_folding or target[0] == cp:
                raise ValueError("invalid simple/common folding")
            simple_folding[cp] = target[0]
    if not simple_folding or any(target in simple_folding for target in simple_folding.values()):
        raise ValueError("simple folding is not idempotent")
    properties = {"Cased": [], "Case_Ignorable": []}
    for line in sources["DerivedCoreProperties.txt"].decode().splitlines():
        fields = [f.strip() for f in line.split("#", 1)[0].split(";")]
        if len(fields) != 2 or fields[1] not in properties:
            continue
        bounds = fields[0].split("..")
        start, end = scalar(bounds[0]), scalar(bounds[-1])
        if start > end or (start <= 0xDFFF and end >= 0xD800):
            raise ValueError("invalid property range")
        ranges = properties[fields[1]]
        if ranges and start <= ranges[-1][1]:
            raise ValueError("overlapping or unordered property ranges")
        if ranges and start == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], end)
        else:
            ranges.append((start, end))
    lines = [
        "// Generated by tools/generate-case-mappings.py. Do not edit.",
        f"// Unicode {VERSION}: full default casing, simple folding and Final_Sigma properties.",
        "// Copyright © 2026 Unicode, Inc. See third-party/unicode/LICENSE.",
    ]
    for name, digest in SOURCES.items():
        lines += [f"// Source: https://www.unicode.org/Public/{VERSION}/ucd/{name}", f"// SHA-256: {digest}"]
    for name, table in mappings.items():
        lines += ["", f"pub(crate) const {name}: &[(u32, &[u16])] = &["]
        for cp, target in sorted(table.items()):
            if target == [cp]:
                continue
            if not target:
                raise ValueError("empty default mapping")
            units = []
            for point in target:
                if point <= 0xFFFF:
                    units.append(point)
                else:
                    point -= 0x10000
                    units += [0xD800 + (point >> 10), 0xDC00 + (point & 0x3FF)]
            mapped = ", ".join(f"0x{u:04x}" for u in units)
            lines.append(f"    (0x{cp:04x}, &[{mapped}]),")
        lines.append("];")
    lines += ["", "pub(crate) const SIMPLE_CASE_FOLD: &[(u32, u32)] = &["]
    lines += [f"    (0x{cp:04x}, 0x{target:04x})," for cp, target in sorted(simple_folding.items())]
    lines.append("];")
    for name, ranges in properties.items():
        if not ranges:
            raise ValueError(f"missing property: {name}")
        lines += ["", f"pub(crate) const {name.upper()}: &[(u32, u32)] = &["]
        lines += [f"    (0x{start:04x}, 0x{end:04x})," for start, end in ranges]
        lines.append("];")
    return ("\n".join(lines) + "\n").encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", type=Path, help="directory containing pinned UCD files")
    parser.add_argument("--check", action="store_true", help="verify tables without writing")
    args = parser.parse_args()
    sources = {}
    for name in SOURCES:
        if args.source:
            sources[name] = args.source.joinpath(name).read_bytes()
        else:
            with urllib.request.urlopen(f"https://www.unicode.org/Public/{VERSION}/ucd/{name}", timeout=60) as response:
                sources[name] = response.read(4 * 1024 * 1024)
    generated = generate(sources)
    if args.check:
        if OUTPUT.read_bytes() != generated:
            raise SystemExit("Case tables differ from the pinned data. Regenerate and review them.")
        print(f"Verified Unicode {VERSION} case tables.")
    else:
        OUTPUT.write_bytes(generated)
        print(f"Generated Unicode {VERSION} case tables.")


if __name__ == "__main__":
    main()
