"""Generate exact ECMAScript Unicode property aliases from pinned Unicode data."""

import argparse
import hashlib
from pathlib import Path
import re
import urllib.request

VERSION = "18.0.0"
SOURCES = {
    "PropertyAliases.txt": "83b8df695f9da543dba02b0be2b8bd72f0b52836ad264be113c6d285021ef025",
    "PropertyValueAliases.txt": "06c4c8eaf7b0bf34abe73b113da1215bd784ac254d4c223600b90267caa4bbbd",
}
OUTPUT = Path(__file__).resolve().parent.parent / "crates/spite-parser/src/regexp/property_data.rs"

# ECMA-262 edition 17's table-binary-unicode-properties is an explicit whitelist.
# Do not import other UCD aliases or properties. In particular, WSpace is excluded.
# https://262.ecma-international.org/17.0/#table-binary-unicode-properties
BINARY = """
ASCII
ASCII_Hex_Digit AHex
Alphabetic Alpha
Any
Assigned
Bidi_Control Bidi_C
Bidi_Mirrored Bidi_M
Case_Ignorable CI
Cased
Changes_When_Casefolded CWCF
Changes_When_Casemapped CWCM
Changes_When_Lowercased CWL
Changes_When_NFKC_Casefolded CWKCF
Changes_When_Titlecased CWT
Changes_When_Uppercased CWU
Dash
Default_Ignorable_Code_Point DI
Deprecated Dep
Diacritic Dia
Emoji
Emoji_Component EComp
Emoji_Modifier EMod
Emoji_Modifier_Base EBase
Emoji_Presentation EPres
Extended_Pictographic ExtPict
Extender Ext
Grapheme_Base Gr_Base
Grapheme_Extend Gr_Ext
Hex_Digit Hex
IDS_Binary_Operator IDSB
IDS_Trinary_Operator IDST
ID_Continue IDC
ID_Start IDS
Ideographic Ideo
Join_Control Join_C
Logical_Order_Exception LOE
Lowercase Lower
Math
Noncharacter_Code_Point NChar
Pattern_Syntax Pat_Syn
Pattern_White_Space Pat_WS
Quotation_Mark QMark
Radical
Regional_Indicator RI
Sentence_Terminal STerm
Soft_Dotted SD
Terminal_Punctuation Term
Unified_Ideograph UIdeo
Uppercase Upper
Variation_Selector VS
White_Space space
XID_Continue XIDC
XID_Start XIDS
"""
# https://262.ecma-international.org/17.0/#table-binary-unicode-properties-of-strings
STRINGS = """
Basic_Emoji Emoji_Keycap_Sequence RGI_Emoji RGI_Emoji_Flag_Sequence
RGI_Emoji_Modifier_Sequence RGI_Emoji_Tag_Sequence RGI_Emoji_ZWJ_Sequence
"""


def records(data):
    for line in data.decode("utf-8").splitlines():
        fields = [field.strip() for field in line.split("#", 1)[0].split(";")]
        if len(fields) > 1:
            yield fields


def generate(sources):
    for name, digest in SOURCES.items():
        if hashlib.sha256(sources[name]).hexdigest() != digest:
            raise ValueError(f"{name} differs from the pinned SHA-256")
    aliases = {fields[1]: set(fields) for fields in records(sources["PropertyAliases.txt"])}
    binary = []
    for line in BINARY.strip().splitlines():
        names = line.split()
        if names[0] not in ("ASCII", "Any", "Assigned"):
            if not set(names).issubset(aliases[names[0]]):
                raise ValueError(f"unrecognized binary property alias: {line}")
        binary.extend(names)
    # Script_Extensions uses Script's value aliases (there are no scx records).
    tables = {"GENERAL_CATEGORY": [], "SCRIPT": [], "BINARY": binary, "STRINGS": STRINGS.split()}
    for fields in records(sources["PropertyValueAliases.txt"]):
        target = {"gc": "GENERAL_CATEGORY", "sc": "SCRIPT"}.get(fields[0])
        if target:
            # Some short and long names are identical (for example Thai).
            names = set(fields[1:])
            if names.intersection(tables[target]):
                raise ValueError(f"value alias belongs to multiple records: {fields}")
            tables[target].extend(names)
    lines = [
        "// Generated by tools/generate-regexp-properties.py. Do not edit.",
        "// ECMA-262 edition 17 exact property aliases and Unicode 18 value aliases.",
        "// https://262.ecma-international.org/17.0/#sec-runtime-semantics-unicodematchproperty-p",
        "// Copyright © 2026 Unicode, Inc. See third-party/unicode/LICENSE.",
    ]
    for name, digest in SOURCES.items():
        lines += [f"// Source: https://www.unicode.org/Public/{VERSION}/ucd/{name}", f"// SHA-256: {digest}"]
    for name, values in tables.items():
        if not values or len(values) != len(set(values)):
            raise ValueError(f"empty or duplicate aliases in {name}")
        if any(not re.fullmatch(r"[A-Za-z_0-9]+", value) for value in values):
            raise ValueError(f"invalid alias in {name}")
        lines += ["", f"pub(super) const {name}: &[&str] = &["]
        lines += [f'    "{value}",' for value in sorted(values)]
        lines += ["];"]
    return ("\n".join(lines) + "\n").encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", type=Path, help="directory containing pinned UCD files")
    parser.add_argument("--check", action="store_true", help="verify tables without writing")
    args = parser.parse_args()
    sources = {}
    for name in SOURCES:
        if args.source:
            sources[name] = args.source.joinpath(name).read_bytes()
        else:
            with urllib.request.urlopen(f"https://www.unicode.org/Public/{VERSION}/ucd/{name}", timeout=60) as response:
                sources[name] = response.read(1024 * 1024)
    generated = generate(sources)
    if args.check:
        if OUTPUT.read_bytes() != generated:
            raise SystemExit("RegExp property tables differ from the pinned data. Regenerate and review them.")
        print(f"Verified Unicode {VERSION} RegExp property aliases.")
    else:
        OUTPUT.write_bytes(generated)
        print(f"Generated Unicode {VERSION} RegExp property aliases.")


if __name__ == "__main__":
    main()
