"""Generate digest-pinned Unicode normalization mappings and composition data."""

import argparse
import hashlib
from pathlib import Path
import urllib.request

VERSION = "18.0.0"
SOURCES = {
    "UnicodeData.txt": "0736451de439ae7baf1425136617da495e09ee5afbe6e394374db7009ea08950",
    "DerivedNormalizationProps.txt": "98ac7f67d985fe781e317f6182e885e94cabb0c314769e6dd73e48b226931ccd",
}
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates/spite-core/src/normalization_data.rs"
TEST_FILE = ROOT / "crates/spite-runtime/tests/fixtures/NormalizationTest-18.0.0.txt"
TEST_SHA256 = "25a50d816764b04abfb4a646d3eb2b2a803284c3873d9a06757b94fe4513dde3"


def scalar(value):
    point = int(value, 16)
    if not (0 <= point <= 0x10FFFF) or 0xD800 <= point <= 0xDFFF:
        raise ValueError("invalid Unicode scalar")
    return point


def generate(sources):
    for name, digest in SOURCES.items():
        if hashlib.sha256(sources[name]).hexdigest() != digest:
            raise ValueError(f"{name} differs from the pinned SHA-256")
    mappings = {}
    classes = {}
    previous = -1
    for line in sources["UnicodeData.txt"].decode().splitlines():
        fields = line.split(";")
        if len(fields) != 15:
            raise ValueError("invalid UnicodeData record")
        point = int(fields[0], 16)
        if point <= previous or point > 0x10FFFF:
            raise ValueError("unordered UnicodeData records")
        previous = point
        combining = int(fields[3])
        if not 0 <= combining <= 255:
            raise ValueError("invalid combining class")
        if combining:
            scalar(fields[0])
            if fields[1].endswith(('First>', 'Last>')):
                raise ValueError("unhandled nonzero combining-class range")
            classes[point] = combining
        parts = fields[5].split()
        if parts:
            scalar(fields[0])
            compatibility = parts[0].startswith('<')
            if compatibility:
                if not parts.pop(0).endswith('>'):
                    raise ValueError("invalid decomposition tag")
            if not parts:
                raise ValueError("empty decomposition")
            mappings[point] = (compatibility, [scalar(part) for part in parts])
    # Verify the complete decomposition graph before emitting recursive mappings.
    states = {}
    for point in mappings:
        pending = [(point, False)]
        while pending:
            point, expanded = pending.pop()
            if expanded:
                states[point] = 2
            elif states.get(point) == 1:
                raise ValueError("cyclic decomposition graph")
            elif states.get(point) != 2:
                states[point] = 1
                pending.append((point, True))
                pending.extend((child, False) for child in mappings[point][1] if child in mappings)
    exclusions = set()
    previous = -1
    for line in sources['DerivedNormalizationProps.txt'].decode().splitlines():
        fields = [part.strip() for part in line.split('#', 1)[0].split(';')]
        if len(fields) != 2 or fields[1] != 'Full_Composition_Exclusion':
            continue
        bounds = fields[0].split('..')
        start, end = scalar(bounds[0]), scalar(bounds[-1])
        if start <= previous or start > end:
            raise ValueError("unordered composition exclusions")
        previous = end
        exclusions.update(range(start, end + 1))
    if not exclusions:
        raise ValueError("missing composition exclusions")
    compositions = {}
    for point, (compatibility, parts) in mappings.items():
        if compatibility or point in exclusions:
            continue
        if len(parts) != 2 or classes.get(parts[0], 0) != 0 or classes.get(point, 0) != 0:
            raise ValueError("unhandled canonical composition")
        key = tuple(parts)
        if key in compositions:
            raise ValueError("ambiguous canonical composition")
        compositions[key] = point
    ranges = []
    for point, combining in sorted(classes.items()):
        if ranges and point == ranges[-1][1] + 1 and combining == ranges[-1][2]:
            ranges[-1] = (ranges[-1][0], point, combining)
        else:
            ranges.append((point, point, combining))
    lines = [
        "// Generated by tools/generate-normalization.py. Do not edit.",
        f"// Unicode {VERSION}: decompositions, combining classes, and canonical compositions.",
        "// Copyright © 2026 Unicode, Inc. See third-party/unicode/LICENSE.",
    ]
    for name, digest in SOURCES.items():
        lines += [f"// Source: https://www.unicode.org/Public/{VERSION}/ucd/{name}", f"// SHA-256: {digest}"]
    lines += ['', '#[rustfmt::skip]', 'pub(crate) const DECOMPOSITIONS: &[(u32, bool, &[u32])] = &[']
    for point, (compatibility, parts) in sorted(mappings.items()):
        mapping = ', '.join(f'0x{part:04x}' for part in parts)
        flag = 'true' if compatibility else 'false'
        lines.append(f'    (0x{point:04x}, {flag}, &[{mapping}]),')
    lines += ['];', '', 'pub(crate) const COMBINING_CLASSES: &[(u32, u32, u8)] = &[']
    lines += [f'    (0x{start:04x}, 0x{end:04x}, {combining}),' for start, end, combining in ranges]
    lines += ['];', '', 'pub(crate) const COMPOSITIONS: &[((u32, u32), u32)] = &[']
    lines += [f'    ((0x{a:04x}, 0x{b:04x}), 0x{point:04x}),' for (a, b), point in sorted(compositions.items())]
    lines += ['];']
    return ('\n'.join(lines) + '\n').encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', nargs='?', type=Path, help='directory containing pinned UCD sources')
    parser.add_argument('--check', action='store_true', help='verify checked-in tables without writing')
    args = parser.parse_args()
    if hashlib.sha256(TEST_FILE.read_bytes()).hexdigest() != TEST_SHA256:
        raise SystemExit("The original Unicode normalization oracle differs from its pinned SHA-256.")
    sources = {}
    for name in SOURCES:
        if args.source:
            sources[name] = args.source.joinpath(name).read_bytes()
        else:
            with urllib.request.urlopen(f'https://www.unicode.org/Public/{VERSION}/ucd/{name}', timeout=60) as response:
                sources[name] = response.read(4 * 1024 * 1024)
    generated = generate(sources)
    if args.check:
        if OUTPUT.read_bytes() != generated:
            raise SystemExit('Normalization tables differ from the pinned data. Regenerate and review them.')
        print(f'Verified Unicode {VERSION} normalization tables.')
    else:
        OUTPUT.write_bytes(generated)
        print(f'Generated Unicode {VERSION} normalization tables.')


if __name__ == '__main__':
    main()
