#!/usr/bin/env python3
"""Independent shortest-radix reference using Python's exact Fraction arithmetic.

Enumerate adjacent integers at increasing precision, accepting only candidates
whose correctly rounded Fraction-to-float conversion returns the input. This
does not use the runtime's digit generation or explicit midpoint intervals.
"""

import argparse
import math
from fractions import Fraction
from pathlib import Path
import struct


def power(radix, exponent):
    if exponent >= 0:
        return Fraction(radix**exponent)
    return Fraction(1, radix**-exponent)


def rounded(value):
    try:
        return float(value)
    except OverflowError:
        return math.inf


def reference(value, radix):
    exact = Fraction.from_float(value)
    exponent = 0
    while power(radix, exponent) > exact:
        exponent -= 1
    while power(radix, exponent + 1) <= exact:
        exponent += 1
    point = exponent + 1
    for precision in range(1, 65):
        scale = power(radix, point - precision)
        quotient = exact / scale
        lower = quotient.numerator // quotient.denominator
        candidates = [
            s for s in (lower, lower + 1) if rounded(s * scale) == value
        ]
        if not candidates:
            continue
        significand = min(candidates, key=lambda s: (abs(s * scale - exact), s % 2))
        digits = ""
        while significand:
            significand, digit = divmod(significand, radix)
            digits = "0123456789abcdefghijklmnopqrstuvwxyz"[digit] + digits
        point += len(digits) - precision
        digits = digits.rstrip("0")
        if point <= 0:
            return "0." + "0" * -point + digits
        if point >= len(digits):
            return digits + "0" * (point - len(digits))
        return digits[:point] + "." + digits[point:]
    raise AssertionError("binary64 requires fewer than 65 significant digits")


def generate():
    # Adjacent encodings probe asymmetric spacing, subnormal transitions,
    # upper overflow midpoints, and ordinary repeating-radix expansions.
    encodings = [
        0x0000000000000001,
        0x0000000000000002,
        0x000FFFFFFFFFFFFF,
        0x0010000000000000,
        0x0010000000000001,
        0x3FB999999999999A,  # 0.1
        0x3FE0000000000000,  # 0.5
        0x3FEFFFFFFFFFFFFF,
        0x3FF0000000000000,  # 1
        0x3FF0000000000001,
        0x3FF3C083126E978D,  # 1.2345
        0x4340000000000001,  # 2**53 + 2
        0x7FEFFFFFFFFFFFFE,
        0x7FEFFFFFFFFFFFFF,
    ]
    lines = [
        "# Generated by tools/generate-number-radix-fixtures.py; ECMA-262 6.1.6.1.20.",
        "# binary64 bits\tradix\tshortest fixed representation (nearest, ties-even)",
    ]
    cases = [(bits, radix) for bits in encodings for radix in range(2, 37) if radix != 10]
    # Carries and exponent normalization on both sides of radix powers,
    # including powers that are not exactly representable in binary64.
    for radix in range(2, 37):
        if radix == 10:
            continue
        for exponent in (-20, 20):
            value = rounded(power(radix, exponent))
            bits = int.from_bytes(struct.pack(">d", value), "big")
            cases.extend((neighbor, radix) for neighbor in (bits - 1, bits, bits + 1))
    for bits, radix in cases:
        value = struct.unpack(">d", bits.to_bytes(8, "big"))[0]
        lines.append(f"{bits:016x}\t{radix}\t{reference(value, radix)}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = (
        Path(__file__).resolve().parents[1]
        / "crates/spite-runtime/tests/fixtures/number_radix.tsv"
    )
    expected = generate()
    if args.check:
        if path.read_text() != expected:
            raise SystemExit("Number radix fixtures need regeneration")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected)


if __name__ == "__main__":
    main()
